### ISSUE TITLE
`mlflavors` cannot save and load Deep Learning `sktime` estimators

### ISSUE THREAD

**Issue by achieveordie** [ml-toolkits/mlflavors#27]
**Describe the bug**
This bug was reported [here](https://github.com/sktime/sktime/issues/5324) where we get the following error when trying to save the estimator using `mlflavors`:

```python
AttributeError: 'LSTMFCNClassifier' object has no attribute 'model_'
```

This was mainly due to the bypassing of sktime-native serialization in support of directly serializing it using `pickle` or `cloudpickle`.

**Code to reproduce issue**
``` python
from sktime.classification.deep_learning.lstmfcn import LSTMFCNClassifier
from mlflavors.sktime import save_model, load_model

from sktime.datasets import load_italy_power_demand
X_train, y_train = load_italy_power_demand(split="train", return_type="numpy3D")
X_new, _ = load_italy_power_demand(split="test", return_type="numpy3D")
classifier=LSTMFCNClassifier(verbose=2,n_epochs=5)
classifier.fit(X_train,y_train)
save_model(sktime_model=classifier,path='classifier')
classifier=load_model(model_uri='classifier') 
classifier.predict(X_new)
```

**Expected behavior**
It should save and load like any other estimator would. It is important to note that tensorflow models cannot be pickled directly (at least using the standard `pickle` module).

This bug has been fixed in v0.24.1 release of `sktime` and I also wanted to fix it here so users using `mlflavors` directly do not face the same issue. I'll open a PR making the same changes within a day.

**Screenshots**

**Comment by benjaminbluhm** [comment]
@achieveordie Thank you for raising this issue and contributing!
